name: Registrar Pushes

on:
  push:
    branches:
      - main 

jobs:
  registrar_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Obtener detalles del push y registrar
        run: |
          FECHA_HORA=$(TZ="America/El_Salvador" date +"%Y-%m-%d %H:%M:%S %Z")
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          AUTHOR_NAME=$(git log -1 --pretty=%an)
          AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
          
          echo "Fecha y Hora: $FECHA_HORA" >> push_log.txt
          echo "Commit SHA: $COMMIT_SHA" >> push_log.txt
          echo "Mensaje del Commit: $COMMIT_MESSAGE" >> push_log.txt
          echo "Autor: $AUTHOR_NAME <$AUTHOR_EMAIL>" >> push_log.txt
          echo "---" >> push_log.txt
          
          cat push_log.txt 
      
      - name: Subir archivo de log al repositorio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(logs): Actualizar registro de pushes"
          files: push_log.txt
